[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "https://api.tion.work/api/:splat"
  status = 200

[build.environment]
  NEXT_PUBLIC_API_URL = "https://api.tion.work"
  NEXT_PUBLIC_SITE_URL = "https://docs.dev.tion.work"
