// SEO元数据生成器
export interface SEOConfig {
  title: string;
  description: string;
  keywords: string[];
  locale: string;
  alternateLocales: string[];
}

export const seoConfigs: Record<string, SEOConfig> = {
  zh: {
    title: "dev.tion.work - 现代化开发者工具集合平台",
    description:
      "为开发者提供一站式解决方案，包含代码处理、数据处理、安全工具等30+个实用工具。零注册使用，实时处理，响应式设计。",
    keywords: [
      "开发者工具",
      "代码格式化",
      "数据处理",
      "安全工具",
      "在线工具",
      "开发效率",
      "JSON格式化",
      "JSON格式化器",
      "JSON美化",
      "JSON beautifier",
      "JSON prettifier",
      "Base64编码",
      "Base64编码器",
      "Base64解码",
      "密码生成器",
      "密码生成工具",
      "随机密码",
      "时间戳转换",
      "时间戳转换器",
      "Unix时间戳",
      "二维码生成",
      "QR码生成器",
      "二维码制作",
      "URL编码",
      "URL编码器",
      "URL解码",
      "哈希生成",
      "哈希计算器",
      "MD5生成器",
      "SHA256生成器",
      "颜色选择器",
      "颜色选择工具",
      "颜色代码",
      "文本对比",
      "文本比较工具",
      "文件对比",
      "SQL格式化",
      "SQL格式化器",
      "SQL美化",
      "XML格式化",
      "XML格式化器",
      "XML美化",
      "YAML转换",
      "YAML转换器",
      "YAML格式化",
      "CSV转换",
      "CSV转换器",
      "CSV格式化",
      "Markdown转换",
      "Markdown转换器",
      "Markdown编辑器",
    ],
    locale: "zh_CN",
    alternateLocales: ["en_US", "ja_JP"],
  },
  en: {
    title: "dev.tion.work - Modern Developer Tools Platform",
    description:
      "One-stop solution for developers with 30+ tools including code processing, data processing, security tools. Zero registration required, real-time processing, responsive design.",
    keywords: [
      "developer tools",
      "code formatter",
      "data processing",
      "security tools",
      "online tools",
      "development efficiency",
      "JSON formatter",
      "JSON beautifier",
      "JSON prettifier",
      "JSON validator",
      "JSON minifier",
      "Base64 encoder",
      "Base64 decoder",
      "Base64 encode",
      "password generator",
      "random password",
      "strong password",
      "timestamp converter",
      "Unix timestamp",
      "date converter",
      "QR code generator",
      "QR code maker",
      "QR code creator",
      "URL encoder",
      "URL decoder",
      "URL encode",
      "hash generator",
      "hash calculator",
      "MD5 generator",
      "SHA256 generator",
      "color picker",
      "color selector",
      "color code",
      "hex color",
      "text diff",
      "text compare",
      "file diff",
      "text comparison",
      "SQL formatter",
      "SQL beautifier",
      "SQL prettifier",
      "XML formatter",
      "XML beautifier",
      "XML prettifier",
      "YAML converter",
      "YAML formatter",
      "YAML validator",
      "CSV converter",
      "CSV formatter",
      "CSV validator",
      "Markdown converter",
      "Markdown editor",
      "Markdown formatter",
    ],
    locale: "en_US",
    alternateLocales: ["zh_CN", "ja_JP"],
  },
  ja: {
    title: "dev.tion.work - モダンな開発者ツールプラットフォーム",
    description:
      "コード処理、データ処理、セキュリティツールなど30以上のツールを提供する開発者向けワンストップソリューション。登録不要、リアルタイム処理、レスポンシブデザイン。",
    keywords: [
      "開発者ツール",
      "コードフォーマッター",
      "データ処理",
      "セキュリティツール",
      "オンラインツール",
      "開発効率",
      "JSONフォーマッター",
      "JSONビューティファイアー",
      "JSONプリティファイアー",
      "JSONバリデーター",
      "JSONミニファイアー",
      "Base64エンコーダー",
      "Base64デコーダー",
      "Base64エンコード",
      "パスワードジェネレーター",
      "ランダムパスワード",
      "強力なパスワード",
      "タイムスタンプコンバーター",
      "Unixタイムスタンプ",
      "日付コンバーター",
      "QRコードジェネレーター",
      "QRコードメーカー",
      "QRコードクリエイター",
      "URLエンコーダー",
      "URLデコーダー",
      "URLエンコード",
      "ハッシュジェネレーター",
      "ハッシュ計算機",
      "MD5ジェネレーター",
      "SHA256ジェネレーター",
      "カラーピッカー",
      "カラーセレクター",
      "カラーコード",
      "16進カラー",
      "テキスト差分",
      "テキスト比較",
      "ファイル差分",
      "テキスト比較ツール",
      "SQLフォーマッター",
      "SQLビューティファイアー",
      "SQLプリティファイアー",
      "XMLフォーマッター",
      "XMLビューティファイアー",
      "XMLプリティファイアー",
      "YAMLコンバーター",
      "YAMLフォーマッター",
      "YAMLバリデーター",
      "CSVコンバーター",
      "CSVフォーマッター",
      "CSVバリデーター",
      "Markdownコンバーター",
      "Markdownエディター",
      "Markdownフォーマッター",
    ],
    locale: "ja_JP",
    alternateLocales: ["zh_CN", "en_US"],
  },
};

export function getSEOConfig(language: string = "zh"): SEOConfig {
  return seoConfigs[language] || seoConfigs.zh;
}

export function generateHreflangTags(baseUrl: string) {
  return [
    { rel: "alternate", hrefLang: "zh-CN", href: baseUrl },
    { rel: "alternate", hrefLang: "en-US", href: baseUrl },
    { rel: "alternate", hrefLang: "ja-JP", href: baseUrl },
    { rel: "alternate", hrefLang: "x-default", href: baseUrl },
  ];
}
